### ISSUE TITLE
List when used with bottomUp= true it only works in correctly until the list size is 50

### ISSUE THREAD

**Issue by veeramarni** [phated/grunt-enyo-init#1]
Seems like due to the pagesize set to 50, the list would not work as expected if the list size grows over 50 as we expect the latest addition to the list to be bottom but it goes to the top. 

Is this expected or there is workaround for this issue?

**Comment by phated** [comment]
Don't use this library.  I thought I deprecated, but I actually deprecated its successor - https://www.npmjs.com/package/enyo
